on:
  workflow_dispatch:
    inputs:
      pass:
        type: string
        required: true

jobs:
  call-reuable:
    uses: mlucabrera/workflowcallexample/.github/workflows/reusable-workflow.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      envPAT: ${{ inputs.pass }}
