on:
  workflow_dispatch:
    inputs:
      pass:
        type: string
        required: true

jobs:
  call-reuable:
    uses: mlucabrera/workflowcallexample/.github/workflows/reusable.yaml@main
    secrets:
      envPAT: ${{ inputs.pass }}
