on:
  workflow_dispatch:
    inputs:
      pass:
        type: string
        required: true

jobs:
  call-reusable:
    uses: mluzcabrera/workflowcallexample/.github/workflows/reusable.yaml@main
    secrets:
      envPAT: 789456
