on:
  workflow_call:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: string
        value: 'mlcbtag'
    secrets:
      cacasecret:
        required: true

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 
      - name: I Print passwords cause I don't care
        run: echo  The password is ${{ secrets.cacasecret }} 
